language: node_js
node_js:
  - 4
script:
- bash .build.sh
after_success:
- bash .deploy.sh
env:
  global:
   secure: "XpsGlM8EyYf5kIXxpkQ3BmPEmBQ6RkgKfrOVEPpmvoaSuCMUls1dQZ01qqs5z9/f9xZpXrwYY+DHkKNQAyskMrF7L+cxzngF/yng9Ck3HFo7hA2kisGJzRaTFQez5CBNXTXnaSJonzAVrFGPCcVCcxFIh/XgdatWsnJK6/UWBeF+werDiGK7F3onIuNiFBjFN4ldb8xDUafwzKF7q4lbNFSGyAVfrYzEyqJhNPQzRtJvWxxqNrdl7e3iJvB0HTftH3gCJKtLCWYtv/5ctMC5Ma7EnyJFYmLJvtu2uUJoVoIj9SlgR7lyB5Bl89BszC8b6xjgCgog3ytuwlN3IIvaeHqaUvfk1jZIb2/iZaA/AixMZjX7FlujdtuMQuMquEu4r8rCk+ALjXbkKAWILY2CsbNC3scj7sh8G8qeMEgRXG2hFQlxUheoH6Ax3NQ4nAtH9Q3OlvboKujWmIgXmUmCWi8J6+V+FjqmCMvc8brTqDAcoVBkdZILlaiCpMuedq4mkJh+MywX22YBUd8aCqz7ndA1UEBP8KKyzfU50TtEh0S2+ywn5W/AP8estkixPEqSj9NQ43EIm5JA7jzWMgJC4K1PCjv8wiXA+XRzOB/2Be+irlyRRCAWbLFWrnESmdfsl3rLmzdtCOveLwFpSup7qrQ23juTHpuLomC/CO018hs="
notifications:
  slack:
    secure: llNnXYQ/1R8QTDvodbM5MfLJMIrOSvYMvJY7Btit0vbwXfEgCpcoPNgQZK0Ol1yergnWkwwWNhMvBi5TQEaCJq5R7jHjD0XDun7lgrVMsF3TdpZXq1Op7iHpO2MfojDbu6owNIbe1jsX0LZTud48KJkNXInnbVPzfOwlTUgweXuUAs3RFWb7+Z8KcPa5pBbVIUj363DWmCYzB0MfvcYq7u7ualCY/qgiKG1/KIeHUjOoRfJnpzZztHHkQPkpqvD00DnHgLkcAXg5SPRon9fiv6drDXFOtQ7juI2pSHiBpsmvFKAjq6w83MMnNUyAzRNRWPwTk9TKWJiM2iQ+I4DWm4FOq4GHOxoXami094aiuv4AznMumZRIuN33+Ac/OsFdo2v1t/Efjx1sZyTGp/uYvMKtRtLkiO06r1bhowSkpseAv2ivbAcJGqupYvCApJZPYsF8EM2Jx1MY2Nw2QpBK1Y1BYvbS0UiTAVa7e6ECHrys1+wj07l8zvazJoa2SF/vss7KbCJR6G8qVtIgW2HaeWZeS8leFfzXC/v658zrp9TQnj4BK5JFQISyLLBzmxWPsWpwtCoMJH6z4WxIioy9yiBD//6ZMqsSi9cFbtMtEFR8BesQlOm380I1pjn4SaNr4H6LyX3Lzog0lylXDkP5Q51KjivslS/fZbwsL7/p3dk=
